// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHbgHhe-AC_LdbBwPrxOMXgBc4hetB2o0',
    appId: '1:960516979414:web:789aef1c3984cbd78e6777',
    messagingSenderId: '960516979414',
    projectId: 'presence-71d4a',
    authDomain: 'presence-71d4a.firebaseapp.com',
    storageBucket: 'presence-71d4a.appspot.com',
    measurementId: 'G-33CYQND99W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW0tM25EIRLEG4k69SqE8wHHECei7ORfU',
    appId: '1:960516979414:android:eff530e4f9557ac48e6777',
    messagingSenderId: '960516979414',
    projectId: 'presence-71d4a',
    storageBucket: 'presence-71d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAurBhTO8w3E-Gb5t3PhfUu-4_IFjRF4-o',
    appId: '1:960516979414:ios:c00e09a70c3bfe268e6777',
    messagingSenderId: '960516979414',
    projectId: 'presence-71d4a',
    storageBucket: 'presence-71d4a.appspot.com',
    iosClientId: '960516979414-np689neo0b51ufjmfcacj66s11hkdah6.apps.googleusercontent.com',
    iosBundleId: 'com.mrezkys.presence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAurBhTO8w3E-Gb5t3PhfUu-4_IFjRF4-o',
    appId: '1:960516979414:ios:a688ee239af330068e6777',
    messagingSenderId: '960516979414',
    projectId: 'presence-71d4a',
    storageBucket: 'presence-71d4a.appspot.com',
    iosClientId: '960516979414-r8lmps6ivd9527g9ekolns2kf6mbprr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.presence',
  );
}
